homepage: "https://code.videolan.org/videolan/dav1d"
language: c
sanitizers:
  - address
  - memory
  - undefined
coverage_extra_args: -ignore-filename-regex=.*dump.h
architectures:
  - x86_64
main_repo: 'https://code.videolan.org/videolan/dav1d.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

