homepage: "https://tukaani.org/xz/"
language: c
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/tukaani-project/xz.git'
