homepage: "https://github.com/GoogleCloudPlatform/healthcare-data-harmonization"
language: jvm
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/GoogleCloudPlatform/healthcare-data-harmonization"
