homepage: "https://freedesktop.org/wiki/Software/systemd/"
language: c
builds_per_day: 4
sanitizers:
  - address
  - undefined
  - memory
fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer
main_repo: 'https://github.com/systemd/systemd'
architectures:
  - x86_64
