homepage: "https://github.com/AOMediaCodec/libavif"
language: c
fuzzing_engines:
  - libfuzzer
main_repo: 'https://github.com/AOMediaCodec/libavif.git'
sanitizers:
  - address
  - memory
  - undefined
