main_repo: "https://github.com/mm2/Little-CMS"
homepage: "http://www.littlecms.com/"
language: c
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
